In [33]:
import pandas as pd

In [34]:
dognition_data_aggregated_by_dogid = pd.read_excel('dognition_data_aggregated_by_dogid.xlsx')
dognition_data_aggregated_by_dogid.columns

Index(['Dog ID', 'Total Tests Completed', 'Mean ITI (days)',
       'Mean ITI (minutes)', 'Median ITI (days)', 'Median ITI (minutes)',
       'Time diff between first and last game (days)',
       'Time diff between first and last game (minutes)', 'User ID', 'Gender',
       'Birthday', 'Breed', 'Breed_Type', 'Breed_Group', 'Weight', 'Dog_Fixed',
       'DNA_Tested', 'Dimension', 'Sign_in_Count', 'Max_Dogs', 'Membership_ID',
       'Subscribed', 'City', 'State', 'Zip', 'Country', 'Exclude',
       'Free_Start_User', 'Last_Active_At', 'Membership_Type'],
      dtype='object')

In [36]:
dognition_data_aggregated_by_dogid['Max_Dogs'].unique()

array([ 2.,  1., 13.,  4.,  3.,  7.,  6., 20., 12., 36.,  5.,  8., 10.,
       15.,  0., nan])

In [5]:
dognition_data_aggregated_by_dogid[dognition_data_aggregated_by_dogid['Dimension']=='socialite'].count()

Dog ID                                             871
Total Tests Completed                              871
Mean ITI (days)                                    871
Mean ITI (minutes)                                 871
Median ITI (days)                                  871
Median ITI (minutes)                               871
Time diff between first and last game (days)       871
Time diff between first and last game (minutes)    871
User ID                                            871
Gender                                             871
Birthday                                           871
Breed                                              870
Breed_Type                                         871
Breed_Group                                        871
Weight                                             871
Dog_Fixed                                          871
DNA_Tested                                         871
Dimension                                          871
Sign_in_Count                                      871
Max_Dogs                                           871
Membership_ID                                      871
Subscribed                                         871
City                                               734
State                                              736
Zip                                                734
Country                                            744
Exclude                                            871
Free_Start_User                                    871
Last_Active_At                                     871
Membership_Type                                    871
dtype: int64

In [6]:
dognition_data_aggregated_by_dogid.shape

(17986, 30)

In [5]:
dognition_data_no_aggregation_with_zip_code_correction = pd.read_excel('dognition_data_no_aggregation_with_zip_code_correction.xlsx')
dognition_data_no_aggregation_with_zip_code_correction.columns

Index(['Created_at', 'Updated_at', 'User_ID', 'Dog_ID', 'Test_name',
       'Subcategory_name', 'Gender', 'Birthday', 'Breed', 'Breed_Type',
       'Breed_Group', 'Weight', 'Dog_Fixed', 'DNA_Tested', 'Dimension',
       'Sign_in_Count', 'Max_Dogs', 'Membership_ID', 'Subscribed', 'City',
       'State', 'Zip', 'Country', 'Exclude', 'Free_Start_User',
       'Last_Active_At', 'Membership_Type', 'Rating', 'Rank_by_UserID',
       'Rank_by_DogID'],
      dtype='object')

In [12]:
dognition_data_no_aggregation = pd.read_excel('dognition_data_no_aggregation.xlsx')
dognition_data_no_aggregation.columns

Index(['Created_at', 'Updated_at', 'User_ID', 'Dog_ID', 'Test_name',
       'Subcategory_name', 'Gender', 'Birthday', 'Breed', 'Breed_Type',
       'Breed_Group', 'Weight', 'Dog_Fixed', 'DNA_Tested', 'Dimension',
       'Sign_in_Count', 'Max_Dogs', 'Membership_ID', 'Subscribed', 'City',
       'State', 'Zip', 'Country', 'Exclude', 'Free_Start_User',
       'Last_Active_At', 'Membership_Type', 'Rating', 'Rank_by_UserID',
       'Rank_by_DogID'],
      dtype='object')

In [12]:
print(dognition_data_aggregated_by_dogid.shape)
dognition_data_aggregated_by_dogid.head()

(17986, 30)

,Dog ID,Total Tests Completed,Mean ITI (days),Mean ITI (minutes),Median ITI (days),Median ITI (minutes),Time diff between first and last game (days),Time diff between first and last game (minutes),User ID,Gender,...,Membership_ID,Subscribed,City,State,Zip,Country,Exclude,Free_Start_User,Last_Active_At,Membership_Type
0,fd27b272-7144-11e5-ba71-058fbc01cf0b,21,28.201076,40609.549167,0.004687,6.750000,564.021516,812190.983333,ce134e42-7144-11e5-ba71-058fbc01cf0b,female,...,2.0,1.0,Grand Forks,ND,58201,US,0,0,2015-03-12 00:25:00,2
1,fd27b5ba-7144-11e5-ba71-058fbc01cf0b,20,0.413307,595.162281,0.005845,8.416667,7.852836,11308.083333,ce1353d8-7144-11e5-ba71-058fbc01cf0b,male,...,1.0,1.0,Barre,MA,01005,US,0,0,00:00:00,1
2,fd27b6b4-7144-11e5-ba71-058fbc01cf0b,2,0.009132,13.150000,0.009132,13.150000,0.009132,13.150000,ce135ab8-7144-11e5-ba71-058fbc01cf0b,male,...,1.0,1.0,Darien,CT,06820,US,0,0,00:00:00,1
3,fd27b79a-7144-11e5-ba71-058fbc01cf0b,11,56.115179,80805.858333,0.004433,6.383333,561.151794,808058.583333,ce13507c-7144-11e5-ba71-058fbc01cf0b,male,...,1.0,1.0,Winnetka,IL,60093,US,0,0,2014-09-12 19:26:00,1
4,fd27b86c-7144-11e5-ba71-058fbc01cf0b,31,7.734254,11137.326111,0.000399,0.575000,232.027627,334119.783333,ce135e14-7144-11e5-ba71-058fbc01cf0b,female,...,2.0,1.0,Raleigh,NC,27606,US,1,0,00:00:00,2

In [10]:
print(dognition_data_no_aggregation_with_zip_code_correction.shape)
dognition_data_no_aggregation_with_zip_code_correction.head()

(177481, 30)

,Created_at,Updated_at,User_ID,Dog_ID,Test_name,Subcategory_name,Gender,Birthday,Breed,Breed_Type,...,State,Zip,Country,Exclude,Free_Start_User,Last_Active_At,Membership_Type,Rating,Rank_by_UserID,Rank_by_DogID
0,2013-05-13 16:17:00,2013-05-13 16:17:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Yawn Warm-up,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,1.0,1.0
1,2013-05-22 18:54:00,2013-05-22 18:54:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Yawn Game,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,2.0,2.0
2,2013-05-22 18:55:00,2013-05-22 18:55:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Eye Contact Warm-up,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,3.0,3.0
3,2013-05-22 18:56:00,2013-05-22 18:56:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Eye Contact Game,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,4.0,4.0
4,2013-05-22 18:58:00,2013-05-22 18:58:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Treat Warm-up,Communication,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,5.0,5.0

In [11]:
print(dognition_data_no_aggregation.shape)
dognition_data_no_aggregation.head()

NameError: name 'dognition_data_no_aggregation' is not defined

In [31]:
dognition_data_no_aggregation['Subcategory_name'].nunique()

16

In [20]:

dognition_data_no_aggregation[dognition_data_no_aggregation['Dog_ID']=='fd3d1b44-7144-11e5-ba71-058fbc01cf0b']

,Created_at,Updated_at,User_ID,Dog_ID,Test_name,Subcategory_name,Gender,Birthday,Breed,Breed_Type,...,State,Zip,Country,Exclude,Free_Start_User,Last_Active_At,Membership_Type,Rating,Rank_by_UserID,Rank_by_DogID
0,2013-05-13 16:17:00,2013-05-13 16:17:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Yawn Warm-up,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,1.0,1.0
1,2013-05-22 18:54:00,2013-05-22 18:54:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Yawn Game,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,2.0,2.0
2,2013-05-22 18:55:00,2013-05-22 18:55:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Eye Contact Warm-up,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,3.0,3.0
3,2013-05-22 18:56:00,2013-05-22 18:56:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Eye Contact Game,Empathy,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,4.0,4.0
4,2013-05-22 18:58:00,2013-05-22 18:58:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Treat Warm-up,Communication,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,5.0,5.0
5,2013-05-22 18:59:00,2013-05-22 18:59:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Arm Pointing,Communication,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,6.0,6.0
6,2013-05-22 19:00:00,2013-05-22 19:00:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Foot Pointing,Communication,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,7.0,7.0
7,2013-05-22 19:02:00,2013-05-22 19:02:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Watching,Cunning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,8.0,8.0
8,2013-05-22 19:02:00,2013-05-22 19:02:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Turn Your Back,Cunning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,9.0,9.0
9,2013-05-22 19:02:00,2013-05-22 19:02:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Cover Your Eyes,Cunning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,10.0,10.0
10,2013-05-22 19:02:00,2013-05-22 19:02:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Watching - Part 2,Cunning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,11.0,11.0
11,2013-05-22 19:06:00,2013-05-22 19:06:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,One Cup Warm-up,Memory,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,12.0,12.0
12,2013-05-22 19:07:00,2013-05-22 19:07:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Two Cup Warm-up,Memory,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,13.0,13.0
13,2013-05-22 19:08:00,2013-05-22 19:08:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Memory versus Pointing,Memory,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,14.0,14.0
14,2013-05-22 19:08:00,2013-05-22 19:08:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Memory versus Smell,Memory,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,15.0,15.0
15,2013-05-22 19:36:00,2013-05-22 19:36:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Delayed Cup Game,Memory,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,16.0,16.0
16,2013-07-10 17:33:00,2013-07-10 17:33:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Inferential Reasoning Warm-up,Reasoning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,17.0,17.0
17,2013-07-10 17:33:00,2013-07-10 17:33:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Inferential Reasoning Game,Reasoning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,18.0,18.0
18,2013-07-10 17:33:00,2013-07-10 17:33:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Physical Reasoning Warm-up,Reasoning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,19.0,19.0
19,2013-07-10 17:34:00,2013-07-10 17:34:00,ce134a78-7144-11e5-ba71-058fbc01cf0b,fd3d1b44-7144-11e5-ba71-058fbc01cf0b,Physical Reasoning Game,Reasoning,male,2009,Shih Tzu,Pure Breed,...,NC,27701,US,1,0,2015-02-23 13:39:00,2,NaN,20.0,20.0